[2024-01-21T11:31:12.611-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_2 manual__2024-01-21T19:31:05.770169+00:00 [queued]>
[2024-01-21T11:31:12.619-0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_2 manual__2024-01-21T19:31:05.770169+00:00 [queued]>
[2024-01-21T11:31:12.619-0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:31:12.619-0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-01-21T11:31:12.619-0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T11:31:12.643-0800] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): insert_values_2> on 2024-01-21 19:31:05.770169+00:00
[2024-01-21T11:31:12.645-0800] {standard_task_runner.py:55} INFO - Started process 30180 to run task
[2024-01-21T11:31:12.654-0800] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_2', 'manual__2024-01-21T19:31:05.770169+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmps29izbju']
[2024-01-21T11:31:12.656-0800] {standard_task_runner.py:83} INFO - Job 81: Subtask insert_values_2
[2024-01-21T11:31:12.722-0800] {task_command.py:389} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_2 manual__2024-01-21T19:31:05.770169+00:00 [running]> on host Mittu.
[2024-01-21T11:31:12.784-0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=madhu
AIRFLOW_CTX_DAG_ID=executing_sql_pipeline
AIRFLOW_CTX_TASK_ID=insert_values_2
AIRFLOW_CTX_EXECUTION_DATE=2024-01-21T19:31:05.770169+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-21T19:31:05.770169+00:00
[2024-01-21T11:31:12.785-0800] {sql.py:254} INFO - Executing: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        
[2024-01-21T11:31:12.788-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:31:12.850-0800] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-01-21T11:31:12.850-0800] {sql.py:375} INFO - Running statement: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        , parameters: None
[2024-01-21T11:31:12.851-0800] {sql.py:384} INFO - Rows affected: 4
[2024-01-21T11:31:12.869-0800] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_2, execution_date=20240121T193105, start_date=20240121T193112, end_date=20240121T193112
[2024-01-21T11:31:12.909-0800] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-21T11:31:12.922-0800] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
